---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
    transport:
      elevated: true
      username: Administrator
      password: Cod3Can!

suites:
  - name: default
    run_list:
      # Replace with the name of the COOKBOOK
      - recipe[pull-essentials-windows-repo::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
